### ISSUE TITLE
福袋撤回失效

### ISSUE THREAD

**Issue by zomb-676** [ExerciseBook/QQRobot_AntiFukubukuro#2]
![image](https://user-images.githubusercontent.com/26162862/51824466-50e94780-231d-11e9-806d-53b7932ddc9d.png)
撤回失效了

**Comment by Annabel0530** [comment]
管理员不能撤回管理员吧

**Comment by ExerciseBook** [comment]
那我就关闭了啊。

**Comment by LEORChn** [comment]
@ExerciseBook 这只能运行在CoolQ的Pro版本？会有刚来不知道的人吧
